name: Build and Zip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v0.0.1

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v0.0.1
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./output --no-build

      - name: Create ZIP archive
        run: zip -r build.zip ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v0.0.1
        with:
          name: build-zip
          path: build.zip
